# Generated by Django 4.0.6 on 2022-07-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genre',
            new_name='gendre',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
