# Generated by Django 4.0.6 on 2022-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='description',
            field=models.TextField(default='This is a mixed gender league that takes place weekly on Fridays.'),
        ),
    ]
